FROM ubuntu

RUN apt-get update
RUN apt-get -y dist-upgrade
RUN apt-get install -y openssh-server
RUN apt-get install -y python2.7-dev python-pip
RUN apt-get install -y zlib1g-dev libffi-dev libssl-dev
RUN apt-get install -y libxml2-dev libxslt1-dev
RUN pip install setuptools

# Add and install Python mudules
ADD requirements.txt /src/requirements.txt
RUN cd /src; pip install -r requirements.txt

# Add Resource
ADD . /src

# Expose
EXPOSE 5000

#Run
CMD ["python", "/src/application.py"]


